config/routes.rb
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'User', at: 'auth'
  resources :charges
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      get "/add_to_cart/:product_id" => "stores#stores"
      get "/payment" => "stores#payment"
    end
  end

#  mount_devise_token_auth_for 'User', at: 'auth'
  get 'seller_product' => 'products#seller_product', :as => 'seller_product'
  # devise_for :sellers
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_for :sellers, controllers: { sessions: 'sellers/sessions', registrations: 'sellers/registrations'}
  root 'products#index'
  resources :welcome
  get 'carts/index'
  post 'carts/callback'
  resources :products
#  resources :carts
  resources :carts do
    get 'add_to_cart', on: :member
    post 'add_to_cart', on: :member
  end
  # get '/patients/:id', to: 'patients#show', as: 'patient'
resources :orders do
 root 'products#index'
  get 'placed_order', on: :member
  #  resources :orders do
  #   get 'placed_order', on: :member
  #   post 'placed_order', on: :member
  # end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :order
  has_one :cart_product, dependent: :destroy
  has_one :product, through: :cart_product, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  protect_from_forgery :except => [:callback, :index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @carts = current_user.orders.last.carts
    @orders = current_user.orders.last
  end

  def show
    @product = @cart.product
  end

  def edit
    @product = @cart.product
  end
  
  def update
    @p = params['cart']['quantity']
    if @cart.update_columns(:quantity => @p )
      redirect_to carts_index_path
    end
  end

  def callback
    if params[:data][:object][:metadata][:Order]
      @order = Order.find(params[:data][:object][:metadata][:Order])
      @order.update_attributes(:status => :true)  
    end
  end
 
  def add_to_cart
    @q = 0
    @product = Product.find(params[:id])
    @order = current_user.orders.where(status: false).last
    if @order.nil?
      @order = current_user.orders.new
      @order.save

    end
    if @order.carts.exists?
      @order.carts.each do |c|
        if c.cart_product.product_id == @product.id
          c.increment! :quantity
          @a = @product.price*c.quantity
          c.update_attributes(:rate => @a)
          return
        end
      end
      add_cart()  
    else
      add_cart()  
    end
  end
  
  def destroy
    @cart.destroy
    redirect_to carts_url, notice: 'Remove product successfully.'
  end

  def add_cart
    @cart = @order.carts.new()
    @cart.quantity = 1
    @cart.rate = @product.price
    @cart.save
    @cart_product = CartProduct.new(product_id: @product.id, cart_id: @cart.id)
    @cart_product.save
    redirect_to products_path, notice: 'product add successfully.'
  end
  
  private
    def set_product
      @cart = Cart.find(params[:id])
    end

    # def cart_item_params
    #   params.permit(:product_id)
    # end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<%= form_with(model:@cart, local: true) do |form| %>
  <div class="row">
    <div class="col-sm-4">
      <%= image_tag(@product.avatars.last, height: '450', width: '400') %>   
    </div>

    <div class="col-sm-8" >
      <p>
        <strong>quantity: </strong>
        <%= form.text_field :quantity %> 
      </p>
      <p>
        <strong>Price: </strong>
  	    <%= @cart.rate %>
      </p>
      <p>
  	    <strong>description: </strong>
        <%= @product.description %>
      </p>
      <p type="button" class="btn btn-info">
          <%= form.submit %>
      </p>
    </div> 
  </div>     
<% end %>

app/views/carts/index.html.erb
<% total =0 %>
<% pr =0 %>
<h1>cart</h1>
<table class="table">
  <thead>
  <th>picture</th>
  <th>title</th>
	<th>price</th>
	<th>quantity</th>
  <th>Total</th>
  <thead>
  <tbody>
  	<% @carts.each do |cart| %>
  	  <tr>
        <td><%= image_tag(cart.product.avatars.last, height: '50', width: '40') %></td>
  	    <td><%= cart.product.title %></td>
        <td><%= cart.product.price %></td>
        <td><%= cart.quantity %></td>
        <td><%= cart.rate %></td>
        <td type="button" class="btn btn-info"><%= link_to 'edit',  edit_cart_path(cart) %></td>
        <td type="button" class="btn btn-info"><%= link_to 'remove_product', cart_path(cart), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% total = (total) + (cart.rate) %>
        <% pr = pr + cart.quantity %>

	    </tr>
  	<% end %>    
  </tbody>
 </table>
   <p>total_ammount = <%= total %></p>
   <p>total_quantity = <%= pr %></p>
    <%= render 'charges/new' %>
  <p><%= link_to 'back', products_path %></p>
  