config/routes.rb
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'User', at: 'auth'
  resources :charges
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      get "/add_to_cart/:product_id" => "stores#stores"
      get "/payment" => "stores#payment"
    end
  end

#  mount_devise_token_auth_for 'User', at: 'auth'
  get 'seller_product' => 'products#seller_product', :as => 'seller_product'
  # devise_for :sellers
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_for :sellers, controllers: { sessions: 'sellers/sessions', registrations: 'sellers/registrations'}
  root 'products#index'
  resources :welcome
  get 'carts/index'
  post 'carts/callback'
  resources :products
#  resources :carts
  resources :carts do
    get 'add_to_cart', on: :member
    post 'add_to_cart', on: :member
  end
  # get '/patients/:id', to: 'patients#show', as: 'patient'
resources :orders do
 root 'products#index'
  get 'placed_order', on: :member
  #  resources :orders do
  #   get 'placed_order', on: :member
  #   post 'placed_order', on: :member
  # end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller
  has_many_attached :avatars, dependent: :destroy
  has_one :cart_product, dependent: :destroy
  has_one :cart, through: :cart_product, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
	  @products = Product.all
	end

	def seller_product
    @products = current_seller.products
	end

	def show
	end

	def edit
	end

  def update
	  if @product.update_attributes(product_params)
      flash[:success] = "Task updated successfully"
      redirect_to products_path
    else
      render 'new'
    end
	end
	
	def destroy
    if @product.destroy
      redirect_to seller_product_path
    else
      render 'new'
    end  
	end
	
	def new
		@product = current_seller.products.new
	end

	def create
    @product = current_seller.products.new(product_params)
		if @product.save
      redirect_to new_product_path, note: 'product add successfully'
    else
  		render 'new'
	  end
  end


  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :avatars)    
  end
end


  

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model:@product, local: true) do |form| %>


 <p>
   <%= form.label :title %><br>
   <%= form.text_field :title %>
 </p>

 <p>
   <%= form.label :Quantity %><br>
   <%= form.text_field :quantity %>
 </p>

 <p>
   <%= form.label :Price %><br>
   <%= form.text_field :price %>
 </p>

 <p>
   <%= form.label :Description %><br>
   <%= form.text_field :description %>
 </p>

 <p class="field">
   <%= form.label :avatars %><br />
   <%= form.file_field :avatars%>
 </p>

 <p>
   <%= form.submit %>
 </p>
<% end %>

app/views/products/edit.html.erb
<h1>edit page </h1>
<%= render 'form' %>
<p><%= link_to 'Show', product_path %></p>

app/views/products/index.html.erb
  
  <% if user_signed_in? %>
    </br> <p type="button" class="btn btn-info"><%= link_to 'card', carts_index_path %></p>
  <% end %>

  <% if user_signed_in? %>
    <p type="button" class="btn btn-info"><%= link_to 'my_order', orders_path %></p>
  <% end %>

 <table class="table">
    <thead>
      <tr>
       <th>picture</th>
       <th>title</th>
       <th>Price</th>
       <th>description</th>
       <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= image_tag(product.avatars.last, height: '100', width: '80') %></td>
          <td><%= product.title %></td>
       
          <td><%= product.price %></td>
          <td><%= product.description %></td>
          <td type="button" class="btn btn-info"><%= link_to 'Show', product_path(product) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/products/new.html.erb
<%= render 'form' %>
<p><%= link_to 'back', seller_product_path %></p>

app/views/products/seller_product.html.erb
<p id="notice"><%= notice %></p>

<p class="navbar-text pull-right">
    <% if seller_signed_in? %>
     Logged in as <strong><%= current_seller.email %></strong>.
      <%= link_to 'seller_Edit profile', edit_seller_registration_path, :class => 'navbar-link' %> |
      <%= link_to "seller_Logout", destroy_seller_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "seller_Sign up", new_seller_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "seller_Login", new_seller_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>  

  <% if seller_signed_in? %>
    </br><p type="button" class="btn btn-info"><%= link_to 'New Product', new_product_path %></p>
  <% end %>
  <table class="table">
    <thead>
      <tr>
       <th>title</th>
       <th>Price</th>
       <th>description</th>
       <th colspan="2"></th>
     </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
          <td><%= product.title %></td>
          <td><%= product.price %></td>
          <td><%= product.description %></td>
          <td><%= link_to 'Show', product_path(product) %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>  
      </tr>
    <% end %>
  </tbody>
  </table>

app/views/products/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= image_tag(@product.avatars.last, height: '450', width: '400') %>
    <% if user_signed_in? %>
      <p  class="btn btn-info">
        <%= link_to "Add to Cart", add_to_cart_cart_path(:product_id => @product), :method => :post %></br>
      </p>
    <% end %>     
  </div>
  
  <div class="col-sm-8" >
    <p>
  	  <strong>title: </strong>
    	<%= @product.title %>
    </p>
    
    <p>
    	<strong>Price: </strong>
  	  <%= @product.price %>
    </p>
    <p>
  	  <strong>description: </strong>
    	<%= @product.description %>
    </p>
    <% if seller_signed_in?%>
      <p type="button" class="btn btn-info" >
        <%= link_to 'back', seller_product_path %>
      </p>
    <% else %>
      <p type="button" class="btn btn-info">
        <%= link_to 'back', products_path %>
      </p>
    <% end %>
  </div> 
</div> 
    